update jaeger config to support agent
krakendio/krakend-opencensus pull request #72
Opened 2022-10-25 14:12 UTC by CodyManshack-SAP

This PR addresses issue #71 raised a few days ago.

## Testing this PR with docker
### Prepare KrakenD
1. in your local **krakend-ce** directory, place the following line at the end of the `go.mod` file: `replace github.com/krakendio/krakend-opencensus/v2 v2.0.1 => github.com/CodyManshack-SAP/krakend-opencensus/v2 v2.0.2`
2. run `make docker` to build the krakend executable inside the docker image
3. update the `telemetry/opencensus/exporters/jaeger` **ExtraConfig{}** object in the KrakenD config (`/krakend.json`) with either; `jaeger:6831` for the jaeger agent (UDP) or `http://localhost:14268` for the jaeger collector (HTTP) 

### Prepare Docker
4. create a docker network `docker network create jaeger-tracing`

### Run Containers
5. run **jaeger all-in-one** official docker image with ports bound `docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 --network="jaeger-exporter" jaegertracing/all-in-one:latest`
6. run the built **krakend** docker image with ports bound `docker run -d -p 8080:8080 --mount type=bind,source="$(pwd)"/krakend.json,target=/etc/krakend/krakend.json --network="jaeger-exporter" devopsfaith/krakend:2.1.1`

### View Reported Traces
7. Open `http://localhost:16686/search` in your browser to view the Jaeger UI where the traces are reported

2022-11-18 12:59 UTC, taik0 requested changes

2022-11-18 12:59 UTC, taik0 commented on go.mod
> +replace github.com/krakendio/krakend-opencensus/v2 v2.0.1 => github.com/CodyManshack-SAP/krakend-opencensus/v2 v2.0.2
Can you remove this replace?

2022-11-18 12:59 UTC, taik0 commented on opencensus.go
> +	CollectorEndpoint string `json:"collector_endpoint"`
To not break older configurations, we should maintain the `endpoint` parameter as is.

2022-11-18 12:59 UTC, taik0 commented on exporter/jaeger/jaeger.go
> +		CollectorEndpoint: cfg.Exporters.Jaeger.CollectorEndpoint,
Fix this part because of the rename of `endpoint`/`collector_endpoint`

2022-11-18 14:57 UTC, CodyManshack-SAP commented
@taik0 All issues resolved.

2022-11-21 11:04 UTC, merged

2022-11-21 11:04 UTC, taik0 commented
Thank you for the contribution @CodyManshack-SAP !

2022-11-21 11:17 UTC, CodyManshack-SAP commented
No problem, glad I could help a little. :)

2023-02-03 10:44 UTC, alombarte commented
Documentation and JSON schema updated in v2.2 branches and ready for the next release